# Sidebar navigation

- label: 'Welcome'
  link: '/welcome'  
- label: 'Technical direction'
  link: '/technical-direction'
- label: 'Teamwork'
  link: '/teamwork'
- label: 'Monorepo'
  link: '/monorepo'
- label: 'Code standards'
  link: 'code-standards'
- label: Design Guide
  items:
    - label: 'README.md'
      link: '/docs/README'
    - label: 'Once-Only'
      link: '/docs/once-only'
    - label: 'Resource Oriented Design'
      link: '/docs/resource-oriented-design'
    - label: 'Naming Conventions'
      link: '/docs/naming-conventions'
